id: PE6ED56D6
initial_creation_type: input
source_metadata:
  title: Ngorchen Könchok Lhundrup
  language: en
  description: 'Texts by and about Ngorchen Könchok Lhundrup (ngor chen dkon mchog
    lhun grub, 1497–1557), the prominent Sakya master and tenth abbot of Ngor Monastery:'
  volume:
    49ef03cee3724b5e8e098dbaf6d5d9b4:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Avalokiteśvara
    f670a680fcd94e9b892581d05395ade1:
      title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
        of the Realm of Holy Nāro Khecarī'
      parent: Vajrayoginī
created_at: '2022-03-01T01:00:58.534152'
last_modified_at: '2022-03-01T01:00:58.534158'
